//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTFGStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public int uniqueid { get; set; }
        public string nombre_articulo { get; set; }
        public int und_disponibles { get; set; }
        public string descripcion { get; set; }
    }
}
